# Generated by Django 4.0.4 on 2022-05-01 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0002_rename_thing_spatial_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spatial_data',
            old_name='name',
            new_name='state',
        ),
    ]
