# Generated by Django 4.0.4 on 2022-05-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0003_rename_name_spatial_data_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatial_data',
            name='type',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
