# Generated by Django 4.0.4 on 2022-05-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0004_spatial_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatial_data',
            name='attributes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='spatial_data',
            name='duration',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
