# Generated by Django 4.0.4 on 2022-05-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0005_spatial_data_attributes_spatial_data_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatial_data',
            name='type',
            field=models.CharField(max_length=256),
        ),
    ]
